import Layout from '@components/Layout'
import { query } from 'firebase/firestore'
import Head from 'next/head'
import { useRouter } from 'next/router'
import React from 'react'
import { useQuery } from 'react-query'
import useAuthState from 'src/hooks/useAuthState'
import { findDeclaration } from 'src/lib/declarations'

interface DetailProps {}

const Detail = ({}: DetailProps) => {
  const [user] = useAuthState()
  const userId = user?.uid
  const router = useRouter()
  const docId = router.query.id

  // const { isLoading, data } = useQuery(
  //   ['findDeclaration', [userId, docId]],
  //   () => findDeclaration(userId!, docId!),
  //   {
  //     enabled: !!userId && !!docId,
  //   }
  // )

  return (
    <Layout>
      <Head>
        <title>천국열쇠 챌린지</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="relative w-full overflow-y-auto py-8 px-4 flex flex-col gap-y-4">
        detail
      </div>
    </Layout>
  )
}

export default Detail
