import React, { useEffect, useRef } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { motion } from 'framer-motion'
// import Card from '@components/Card';
import Layout from '@components/Layout'
import CardMotion from '@components/CardMotion'
import FloatingActionButton from '@components/FloatingActionButton'

interface IndexProps {}

const Index = ({}: IndexProps) => {
  const boardRef = useRef<HTMLDivElement>(null)
  const containerX = useRef(0)
  const containerY = useRef(0)

  useEffect(() => {
    if (boardRef.current !== null) {
      const { width, height } = boardRef.current.getBoundingClientRect()
      console.log('컨테이너 너비와 높이: ', width, height)
    }
  }, [])

  return (
    <Layout>
      <Head>
        <title>천국열쇠 챌린지</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Image
        src={'/images/tree.png'}
        alt=""
        width={1501}
        height={1500}
        style={{
          position: 'absolute',
          top: '50%',
          left: 0,
          transform: 'translateY(-50%)',
        }}
        priority={true}
      />

      <div className="relative w-full h-[calc(100%-80px)] z-50">
        <h1 className="text-center font-gamjaFlower text-2xl">
          현재 1,215개 천국열쇠가 생성되었습니다
        </h1>
        <div className="w-full h-full" ref={boardRef}>
          <CardMotion boardRef={boardRef} initialX={0} initialY={0} />
          <CardMotion boardRef={boardRef} initialX={150} initialY={200} />
          <CardMotion boardRef={boardRef} initialX={300} initialY={400} />
        </div>
        <FloatingActionButton />
      </div>
    </Layout>
  )
}

export default Index
