import Layout from '@components/Layout'
import Head from 'next/head'
import React from 'react'

interface signupProps {}

const signup = ({}: signupProps) => {
  return (
    <Layout auth>
      <Head>
        <title>회원가입 | 천국열쇠 챌린지</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Sign-Up</h1>
    </Layout>
  )
}

export default signup
